//! canteiro plane (a) — multi-worker dispatch via a DAG-derived GitHub Actions
//! job graph (theory/CANTEIRO.md §5, "the crux").
//!
//! [`emit_gha`] projects a decomposed [`CiRun`] onto a GitHub Actions workflow:
//! **one job per [`CiNode`]**, each job's `needs:` = that node's DAG edges, each
//! `runs-on: camelot-builder-pleme-eks`. GitHub Actions then schedules those jobs
//! onto **separate** ARC workers, ordered by `needs:` — so a 2-node `build→test`
//! run lands `build` and `test` on two different workers, `test` after `build`.
//!
//! ## HONEST SCOPE — plane (a), stated on the record (never rounded up)
//!
//! This is **plane (a)** of CANTEIRO §5. canteiro's `decompose` *derives* the
//! job graph; **GitHub Actions does the cross-worker scheduling**; canteiro is
//! the DAG **source + emitter**, NOT the cross-worker runtime scheduler. The
//! value canteiro adds here is the *derivation* — one `CiRun` mechanically
//! becomes the multi-worker graph, with `needs:` a faithful projection of the
//! typed DAG edges — not the scheduling itself. The harder plane (shigoto stays
//! the executor *across* workers, dispatching to remote runners itself) is the
//! named remaining crux; it is **not** this.
//!
//! The YAML is emitted through serde structs via `serde_yaml_ng` (★★ TYPED
//! EMISSION — no `format!()` of YAML). The one string built by hand is each
//! job's shell `run:` body (a shell script is inherently a string, assembled via
//! `push_str`, never `format!`), reusing the PROVEN camelot nix setup from
//! `.github/workflows/canteiro-m1.yml` verbatim (upstream nix via
//! `determinate: false`; `pkg-config`+`openssl` for `openssl-sys`).

use serde::Serialize;

use crate::canteiro::{ActionRef, CiRun, DecomposeError, decompose};

/// The ARC runner pool every canteiro CI job targets — the proven camelot label
/// (see `.github/workflows/canteiro-m1.yml`).
const CAMELOT_RUNNER: &str = "camelot-builder-pleme-eks";

/// The `access-tokens`/`github-token` expression the nix installer + private
/// fetches use (mirrors `canteiro-m1.yml`).
const GH_TOKEN_EXPR: &str = "${{ secrets.BOT_PAT || secrets.GITHUB_TOKEN }}";

/// The exact `extra-conf` the proven camelot nix install uses.
const NIX_EXTRA_CONF: &str = "experimental-features = nix-command flakes\n\
     accept-flake-config = true\n\
     sandbox = relaxed\n\
     access-tokens = github.com=${{ secrets.BOT_PAT || secrets.GITHUB_TOKEN }}\n";

/// The header prepended to the emitted workflow — states it is generated (so a
/// hand-edit is a persisted-spec drift the CI test catches) and the plane-(a)
/// honesty. Kept in the emitted bytes so the binary and the round-trip test
/// compare identical output.
const HEADER: &str = "\
# GENERATED by `canteiro-emit-gha` (sui-supercacheci) — do NOT hand-edit.\n\
# The committed file IS the emitter's output (persisted-spec discipline); a\n\
# drift is a CI failure. Regenerate: `cargo run -p sui-supercacheci --bin canteiro-emit-gha`.\n\
#\n\
# canteiro plane (a), the multi-worker dispatch crux (theory/CANTEIRO.md §5):\n\
# `emit_gha` projects a decomposed CiRun onto this job graph — one job per\n\
# CiNode, `needs:` = the DAG edges — and GitHub Actions schedules the jobs onto\n\
# SEPARATE camelot ARC workers. HONEST SCOPE: canteiro DERIVES the graph;\n\
# GitHub SCHEDULES the workers; canteiro is the DAG source + emitter, NOT the\n\
# cross-worker runtime scheduler (that harder plane is the named remaining\n\
# crux). workflow_dispatch-only: a live run is a deliberate operator trigger.\n";

/// A GitHub Actions workflow — the typed emission target.
#[derive(Debug, Serialize)]
pub struct GhaWorkflow {
    name: String,
    #[serde(rename = "on")]
    on: GhaOn,
    /// Ordered by job key (`BTreeMap`) for deterministic byte-output; GitHub
    /// orders *execution* by `needs:`, not by textual position, so alphabetical
    /// keys are correct and stable.
    pub jobs: std::collections::BTreeMap<String, GhaJob>,
}

#[derive(Debug, Serialize)]
struct GhaOn {
    /// Serializes as `workflow_dispatch: {}` — the ONLY trigger, so a live run
    /// is always a deliberate operator dispatch, never automatic on push.
    workflow_dispatch: WorkflowDispatch,
}

#[derive(Debug, Serialize)]
struct WorkflowDispatch {}

/// One GitHub Actions job — the projection of one [`CiNode`].
#[derive(Debug, Serialize)]
pub struct GhaJob {
    name: String,
    #[serde(rename = "runs-on")]
    runs_on: String,
    /// The node's DAG edges. Skipped when empty so a root job carries no
    /// `needs:` key.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub needs: Vec<String>,
    steps: Vec<GhaStep>,
}

/// A workflow step. `untagged` so each variant serializes as its bare fields
/// (no discriminant key) — the three shapes a canteiro job needs.
#[derive(Debug, Serialize)]
#[serde(untagged)]
enum GhaStep {
    /// `- uses: actions/checkout@v4`
    Uses { uses: String },
    /// The proven camelot nix install (upstream nix, `determinate: false`).
    InstallNix {
        name: String,
        uses: String,
        #[serde(rename = "with")]
        with_: NixInstallerWith,
    },
    /// `- name: … / run: |` — the node's real action, nix-shell-wrapped.
    Run { name: String, run: String },
}

#[derive(Debug, Serialize)]
struct NixInstallerWith {
    #[serde(rename = "github-token")]
    github_token: String,
    determinate: bool,
    #[serde(rename = "extra-conf")]
    extra_conf: String,
}

/// Failure of [`emit_gha`] / [`emit_gha_yaml`].
#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    /// The `CiRun` is not a well-formed DAG (dup / dangling dep / cycle).
    #[error("cannot emit a job graph from an invalid CI run: {0}")]
    Decompose(#[from] DecomposeError),
    /// serde_yaml_ng failed to render the typed workflow.
    #[error("serializing the GHA workflow to YAML failed: {0}")]
    Yaml(#[from] serde_yaml_ng::Error),
}

/// The readable job display name (`canteiro · <node>`), built without
/// `format!()` per ★★ TYPED EMISSION.
fn job_display_name(node: &str) -> String {
    let mut s = String::from("canteiro · ");
    s.push_str(node);
    s
}

/// The shell `run:` body for a node's action — the PROVEN camelot build-env from
/// `canteiro-m1.yml` (upstream nix already installed by the InstallNix step;
/// `pkg-config`+`openssl` for `openssl-sys`), then the node's own command+args.
/// A shell script is inherently a string; assembled via `push_str`, never
/// `format!` (the YAML *structure* around it is serde-emitted).
fn run_script(action: &ActionRef) -> String {
    let mut s = String::new();
    s.push_str(
        "# Proven camelot build env (see canteiro-m1.yml): openssl-sys needs\n\
         # pkg-config + the openssl .pc; a bare `nix shell` with only cargo/rustc/gcc\n\
         # lacks them. OPENSSL_NO_VENDOR=1 uses nix's openssl, not a vendored build.\n",
    );
    s.push_str("OPENSSL_DEV=$(nix build --no-link --print-out-paths 'nixpkgs#openssl.dev')\n");
    s.push_str(
        "nix shell nixpkgs#cargo nixpkgs#rustc nixpkgs#gcc nixpkgs#pkg-config nixpkgs#openssl \\\n",
    );
    s.push_str("  --command env \\\n");
    s.push_str("    PKG_CONFIG_PATH=\"$OPENSSL_DEV/lib/pkgconfig\" \\\n");
    s.push_str("    OPENSSL_NO_VENDOR=1 \\\n");
    s.push_str("    ");
    s.push_str(&action.command);
    for arg in &action.args {
        s.push(' ');
        s.push_str(arg);
    }
    s.push('\n');
    s
}

/// The three steps every canteiro job runs: checkout → install nix → run the
/// node's action.
fn steps_for(action: &ActionRef) -> Vec<GhaStep> {
    vec![
        GhaStep::Uses {
            uses: "actions/checkout@v4".to_string(),
        },
        GhaStep::InstallNix {
            name: "Install Nix".to_string(),
            uses: "DeterminateSystems/nix-installer-action@main".to_string(),
            with_: NixInstallerWith {
                github_token: GH_TOKEN_EXPR.to_string(),
                // Upstream nix — Determinate's systemd daemon HANGS on the
                // containerless ARC runner (canteiro-m1.yml's receipt).
                determinate: false,
                extra_conf: NIX_EXTRA_CONF.to_string(),
            },
        },
        GhaStep::Run {
            name: {
                let mut s = String::from("Run ");
                s.push_str(&action.name);
                s
            },
            run: run_script(action),
        },
    ]
}

/// **The plane-(a) morphism.** Project a [`CiRun`] onto a typed GitHub Actions
/// job graph: one [`GhaJob`] per [`CiNode`] (job key = node name), each job's
/// `needs:` = the node's `deps` (the DAG edges), each `runs-on` the camelot ARC
/// pool. The run is `decompose`d first so an invalid DAG (dup / dangling /
/// cycle) is rejected before any graph is emitted.
///
/// # Errors
/// [`EmitError::Decompose`] if the `CiRun` is not a well-formed DAG.
pub fn emit_gha(run: &CiRun) -> Result<GhaWorkflow, EmitError> {
    // Validate the DAG (rejects duplicate / dangling-dep / cyclic runs) so the
    // emitted `needs:` graph is a faithful projection of a real DAG.
    decompose(run)?;

    let mut jobs = std::collections::BTreeMap::new();
    for node in &run.nodes {
        jobs.insert(
            node.name.clone(),
            GhaJob {
                name: job_display_name(&node.name),
                runs_on: CAMELOT_RUNNER.to_string(),
                // `needs:` IS the DAG edge set — a projection of the typed
                // `CiNode.deps`, never a hand-written list.
                needs: node.deps.clone(),
                steps: steps_for(&node.action),
            },
        );
    }

    Ok(GhaWorkflow {
        name: "canteiro-crux".to_string(),
        on: GhaOn {
            workflow_dispatch: WorkflowDispatch {},
        },
        jobs,
    })
}

/// Render a [`CiRun`] to the full workflow YAML (the [`HEADER`] comment + the
/// serde-emitted [`GhaWorkflow`]). The committed `.github/workflows/canteiro-crux.yml`
/// IS this string (persisted-spec discipline).
///
/// # Errors
/// [`EmitError::Decompose`] for an invalid DAG; [`EmitError::Yaml`] on a
/// serialization failure.
pub fn emit_gha_yaml(run: &CiRun) -> Result<String, EmitError> {
    let workflow = emit_gha(run)?;
    let body = serde_yaml_ng::to_string(&workflow)?;
    let mut out = String::from(HEADER);
    out.push('\n');
    out.push_str(&body);
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canteiro::{ActionRef, CiNode, CiRun, EnvClass};

    fn action(name: &str, command: &str, args: &[&str]) -> ActionRef {
        ActionRef {
            name: name.to_string(),
            command: command.to_string(),
            args: args.iter().map(|a| (*a).to_string()).collect(),
        }
    }

    /// The real sui crux run: `build` (cargo build) then `test` (cargo test),
    /// both `env=None` — the ACTUAL commands the live multi-worker proof runs.
    fn sui_crux_run() -> CiRun {
        let build = CiNode::new(
            "build",
            EnvClass::None,
            action("build", "cargo", &["build", "-p", "sui-supercacheci"]),
            vec![],
        );
        let test = CiNode::new(
            "test",
            EnvClass::None,
            action("test", "cargo", &["test", "-p", "sui-supercacheci", "canteiro"]),
            vec!["build".to_string()],
        );
        CiRun {
            workspace: "pleme-io".to_string(),
            repo: "sui".to_string(),
            nodes: vec![build, test],
        }
    }

    #[test]
    fn two_node_run_emits_two_jobs_on_camelot_with_derived_needs() {
        let wf = emit_gha(&sui_crux_run()).expect("emit");
        assert_eq!(wf.jobs.len(), 2, "one job per CiNode");
        let build = wf.jobs.get("build").expect("build job");
        let test = wf.jobs.get("test").expect("test job");
        assert_eq!(build.runs_on, CAMELOT_RUNNER);
        assert_eq!(test.runs_on, CAMELOT_RUNNER);
        // The DAG edge build→test is projected onto test.needs; build is a root.
        assert!(build.needs.is_empty(), "build is a root node — no needs");
        assert_eq!(test.needs, vec!["build".to_string()], "test needs build");
    }

    #[test]
    fn needs_is_derived_from_dag_edges_not_hardcoded() {
        // A fan: a → b, a → c. Both b and c must carry needs:[a]; a carries none.
        let a = CiNode::new("a", EnvClass::None, action("a", "true", &[]), vec![]);
        let b = CiNode::new("b", EnvClass::None, action("b", "true", &[]), vec!["a".into()]);
        let c = CiNode::new("c", EnvClass::None, action("c", "true", &[]), vec!["a".into()]);
        let run = CiRun {
            workspace: "w".to_string(),
            repo: "r".to_string(),
            nodes: vec![a, b, c],
        };
        let wf = emit_gha(&run).expect("emit");
        assert_eq!(wf.jobs.len(), 3);
        assert!(wf.jobs.get("a").unwrap().needs.is_empty());
        assert_eq!(wf.jobs.get("b").unwrap().needs, vec!["a".to_string()]);
        assert_eq!(wf.jobs.get("c").unwrap().needs, vec!["a".to_string()]);
    }

    #[test]
    fn rejects_an_invalid_dag() {
        // A cycle must be refused before any graph is emitted.
        let a = CiNode::new("a", EnvClass::None, action("a", "true", &[]), vec!["b".into()]);
        let b = CiNode::new("b", EnvClass::None, action("b", "true", &[]), vec!["a".into()]);
        let run = CiRun {
            workspace: "w".to_string(),
            repo: "r".to_string(),
            nodes: vec![a, b],
        };
        assert!(matches!(emit_gha(&run), Err(EmitError::Decompose(_))));
    }

    #[test]
    fn yaml_is_workflow_dispatch_only_with_real_cargo_actions() {
        let yaml = emit_gha_yaml(&sui_crux_run()).expect("yaml");
        // workflow_dispatch is the only trigger — a live run is deliberate.
        assert!(yaml.contains("workflow_dispatch"), "has the dispatch trigger");
        assert!(
            !yaml.contains("\non:\n  push")
                && !yaml.contains("pull_request"),
            "no push / pull_request auto-trigger"
        );
        // The actions are the REAL cargo build/test, not trivial true/echo.
        assert!(yaml.contains("cargo build -p sui-supercacheci"), "real cargo build");
        assert!(
            yaml.contains("cargo test -p sui-supercacheci canteiro"),
            "real cargo test"
        );
        // Both jobs target the camelot ARC pool.
        assert!(yaml.contains(CAMELOT_RUNNER));
        // Determinate is off (the containerless-runner fix).
        assert!(yaml.contains("determinate: false"));
        // The header states it is generated + plane (a).
        assert!(yaml.contains("GENERATED by `canteiro-emit-gha`"));
    }
}
